# Generated by Django 4.2.1 on 2023-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyNumber',
            field=models.TextField(unique=True, verbose_name='Номер компании'),
        ),
    ]
